services:
    ext:
        build: .
        volumes:
            - .:/ext
            - node-modules:/ext/node_modules
            - npm-cache:/root/.npm
        working_dir: /ext
        stdin_open: true
        tty: true

volumes:
    node-modules:
    npm-cache:
